export const crops = [
  // Vegetables
  { name: "Spinach", type: "Vegetable", months: [2,3,4,5], soil: "Loamy", moisture: "Moderate", tips: "Sow seeds shallowly", harvest: "30-45 days", img: "/public/Images/potato.png" },
  { name: "Chili", type: "Vegetable", months: [3,4,5,6], soil: "Sandy loam", moisture: "Moderate", tips: "Use well-drained soil", harvest: "70-90 days", img: "/public/images/chili.png" },
  { name: "Tomato", type: "Vegetable", months: [3,4,5,6], soil: "Sandy loam", moisture: "Moderate", tips: "Provide support for vines", harvest: "60-80 days", img: "/public/images/tomato.png" },
  { name: "Potato", type: "Vegetable", months: [1,2,3], soil: "Loamy", moisture: "Moderate", tips: "Plant tubers 4 inches deep", harvest: "70-120 days", img: "/public/Images/potato.png" },
  { name: "Carrot", type: "Vegetable", months: [2,3,4], soil: "Sandy loam", moisture: "Moderate", tips: "Thin seedlings after sprouting", harvest: "70 days", img: "/public/images/carrot.png" },
  { name: "Cabbage", type: "Vegetable", months: [3,4,5], soil: "Loamy", moisture: "Moderate", tips: "Keep soil moist", harvest: "80 days", img: "/public/images/cabbage.png" },
  { name: "Beans", type: "Vegetable", months: [6,7,8], soil: "Loamy", moisture: "Moderate", tips: "Use trellis for support", harvest: "50-60 days", img: "/public/images/beans.png" },
  { name: "Cucumber", type: "Vegetable", months: [5,6,7], soil: "Loamy", moisture: "Moderate", tips: "Provide trellis support", harvest: "50-70 days", img: "/public/images/cucumber.png" },
  { name: "Pumpkin", type: "Vegetable", months: [6,7,8,9,10], soil: "Sandy loam", moisture: "Moderate", tips: "Needs wide spacing", harvest: "90 days", img: "/public/images/pumpkin.png" },
  { name: "Broccoli", type: "Vegetable", months: [3,4,5,9,10], soil: "Loamy", moisture: "Moderate", tips: "Plant seedlings in cool weather", harvest: "70-100 days", img: "/public/images/broccoli.png" },
  { name: "Cauliflower", type: "Vegetable", months: [2,3,4,10,11], soil: "Loamy", moisture: "Moderate", tips: "Keep soil moist", harvest: "70-90 days", img: "/public/images/cauliflower.png" },
  { name: "Eggplant", type: "Vegetable", months: [4,5,6,7,8], soil: "Loamy", moisture: "Moderate", tips: "Provide support for heavy fruits", harvest: "60-90 days", img: "/public/images/eggplant.png" },
  { name: "Zucchini", type: "Vegetable", months: [5,6,7,8], soil: "Loamy", moisture: "Moderate", tips: "Needs wide spacing", harvest: "50-70 days", img: "/public/images/zucchini.png" },
  { name: "Bell Pepper", type: "Vegetable", months: [4,5,6,7,8], soil: "Sandy loam", moisture: "Moderate", tips: "Full sunlight improves color", harvest: "60-80 days", img: "/public/images/bellpepper.png" },
  { name: "Radish", type: "Vegetable", months: [1,2,3,9,10,11], soil: "Sandy loam", moisture: "Moderate", tips: "Harvest small roots quickly", harvest: "30-50 days", img: "/images/radish.png" },
  { name: "Sweet Potato", type: "Vegetable", months: [5,6,7,8,9], soil: "Sandy loam", moisture: "Moderate", tips: "Plant in loose soil", harvest: "90-120 days", img: "/public/images/sweetpotato.png" },
  { name: "Lettuce", type: "Vegetable", months: [2,3,4,5], soil: "Loamy", moisture: "Moderate", tips: "Keep shaded in hot weather", harvest: "40-50 days", img: "/public/images/lettuce.png" },

  // Fruits
  { name: "Dragon Fruit", type: "Fruit", months: [5,6,7,8], soil: "Sandy", moisture: "Low", tips: "Requires climbing support", harvest: "6-7 months", img: "/public/images/dragonfruit.png" },
  { name: "Mango", type: "Fruit", months: [3,4,5], soil: "Loamy", moisture: "Low", tips: "Needs full sunlight", harvest: "3-6 months", img: "/images/mango.png" },
  { name: "Papaya", type: "Fruit", months: [4,5,6], soil: "Sandy loam", moisture: "Moderate", tips: "Plant seedlings carefully", harvest: "5-8 months", img: "/images/papaya.png" },
  { name: "Guava", type: "Fruit", months: [3,4,5], soil: "Loamy", moisture: "Moderate", tips: "Water regularly", harvest: "4-6 months", img: "/images/guava.png" },
  { name: "Strawberry", type: "Fruit", months: [3,4,5], soil: "Loamy", moisture: "Moderate", tips: "Mulch soil to retain moisture", harvest: "60 days", img: "/images/strawberry.png" },
  { name: "Apple", type: "Fruit", months: [2,3,4,9,10,11,12], soil: "Loamy", moisture: "Moderate", tips: "Needs cool climate", harvest: "6-8 months", img: "/images/apple.png" },
  { name: "Banana", type: "Fruit", months: [1,2,3,4,5,6,7,8,9,10,11,12], soil: "Loamy", moisture: "High", tips: "Needs consistent watering", harvest: "9-12 months", img: "/images/banana.png" },
  { name: "Pineapple", type: "Fruit", months: [3,4,5,6,7,8], soil: "Sandy loam", moisture: "Moderate", tips: "Plant crowns in sunny spot", harvest: "18 months", img: "/images/pineapple.png" },
  { name: "Pomegranate", type: "Fruit", months: [4,5,6,7,8,9], soil: "Loamy", moisture: "Low", tips: "Tolerates drought", harvest: "5-6 months", img: "/images/pomegranate.png" },
  { name: "Kiwi", type: "Fruit", months: [5,6,7,8,9], soil: "Loamy", moisture: "Moderate", tips: "Provide climbing support", harvest: "2-3 years for first fruit", img: "/images/kiwi.png" },
  { name: "Blueberry", type: "Fruit", months: [6,7,8], soil: "Acidic loam", moisture: "Moderate", tips: "Needs acidic soil (pH 4.5-5.5)", harvest: "2-3 years", img: "/images/blueberry.png" },
  { name: "Lemon", type: "Fruit", months: [3,4,5,6,7,8,9], soil: "Loamy", moisture: "Moderate", tips: "Plant in full sun", harvest: "6-12 months", img: "/images/lemon.png" },
  { name: "Grapes", type: "Fruit", months: [3,4,5,6,7,8], soil: "Loamy", moisture: "Moderate", tips: "Provide trellis and prune regularly", harvest: "90-120 days", img: "/images/grapes.png" },

  // Grains / Legumes
  { name: "Millet", type: "Grain", months: [1,2,3], soil: "Loamy", moisture: "Low", tips: "Plant seeds directly", harvest: "90 days", img: "/images/millet.png" },
  { name: "Rice", type: "Grain", months: [6,7,8,9], soil: "Clay loam", moisture: "High", tips: "Requires flooded fields", harvest: "120 days", img: "/images/rice.png" },
  { name: "Wheat", type: "Grain", months: [1,2,3], soil: "Loamy", moisture: "Moderate", tips: "Ensure good drainage", harvest: "120 days", img: "/images/wheat.png" },
  { name: "Corn", type: "Grain", months: [4,5,6,7], soil: "Sandy loam", moisture: "Moderate", tips: "Plant seeds 2 inches deep", harvest: "90-100 days", img: "/images/corn.png" },
  { name: "Barley", type: "Grain", months: [1,2,3,9,10], soil: "Loamy", moisture: "Low", tips: "Plant in cool climate", harvest: "90 days", img: "/images/barley.png" },
  { name: "Sorghum", type: "Grain", months: [4,5,6,7,8], soil: "Sandy loam", moisture: "Low", tips: "Drought tolerant", harvest: "90-120 days", img: "/images/sorghum.png" },
  { name: "Lentils", type: "Grain", months: [2,3,4], soil: "Loamy", moisture: "Moderate", tips: "Plant shallow seeds", harvest: "80-100 days", img: "/images/lentils.png" },
  { name: "Chickpeas", type: "Grain", months: [10,11,12,1], soil: "Loamy", moisture: "Low", tips: "Plant in cool weather", harvest: "90 days", img: "/images/chickpeas.png" },
  { name: "Oats", type: "Grain", months: [1,2,3,9,10], soil: "Loamy", moisture: "Moderate", tips: "Plant in cool climate", harvest: "80-100 days", img: "/images/oats.png" },

  // Herbs / Nuts
  { name: "Coriander", type: "Herb", months: [1,2,3,9,10,11], soil: "Loamy", moisture: "Moderate", tips: "Harvest leaves before flowering", harvest: "40-60 days", img: "/images/coriander.png" },
  { name: "Basil", type: "Herb", months: [4,5,6,7,8], soil: "Loamy", moisture: "Moderate", tips: "Keep warm and sunny", harvest: "50-70 days", img: "/images/basil.png" },
  { name: "Mint", type: "Herb", months: [3,4,5,6,7,8,9], soil: "Loamy", moisture: "Moderate", tips: "Water regularly, invasive plant", harvest: "40-60 days", img: "/images/mint.png" },
  { name: "Peanuts", type: "Nut", months: [6,7,8,9], soil: "Sandy loam", moisture: "Moderate", tips: "Harvest after pods mature", harvest: "120 days", img: "/images/peanuts.png" },
  { name: "Cashews", type: "Nut", months: [5,6,7,8,9], soil: "Sandy", moisture: "Low", tips: "Needs tropical climate", harvest: "3-5 years", img: "/images/cashews.png" },
];
